name: invoice_app
description: Invoice generator

publish_to: 'none' # Remove this line if you wish to publish to pub.dev
version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  intl: ^0.18.1
  flutter_mobx: ^2.0.6+5
  mobx: ^2.2.0
  get_it: ^7.6.0
  injectable: ^2.1.1
  dynamic_color: ^1.6.6
  google_fonts: ^5.1.0
  auto_route: ^7.8.0
  pdf: ^3.10.4
  path_provider: ^2.0.15
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  share_plus: ^7.1.0
  image: ^4.0.17 # fix for the PDF package test_api 0.5.1 (0.6.1 available)

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.2
  build_runner: ^2.4.6
  mobx_codegen: ^2.3.0
  injectable_generator: ^2.1.5
  auto_route_generator: ^7.3.0
  hive_generator: ^2.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/currency.json
