name: Release Workflow

on:
  push:
    tags:
      - "v[0-9]+.[0-9]+.[0-9]+"
jobs:
  release:
    runs-on: macos-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - run: mkdir android/keystore

      - name: Decode Keystore
        id: decode_keystore
        uses: timheuer/base64-to-file@v1
        with:
          fileName: 'keystore.jks'
          fileDir: 'android/keystore/'
          encodedString: ${{ secrets.KEYSTORE }}

      - name: Install Java
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.24.2'
          channel: 'stable'

      - run: flutter --version
      - run: flutter pub get
      - run: flutter packages pub run build_runner build --delete-conflicting-outputs

      - run: flutter build apk --release
        env:
          ALIAS: ${{ secrets.KEY_ALIAS }}
          PASS: ${{ secrets.KEY_PASS }}

      - name: Create Git Release
        uses: ncipollo/release-action@v1
        with:
          artifacts: "build/app/outputs/flutter-apk/app-release.apk"
          generateReleaseNotes: true
          draft: true
